---
###############################################################################
# Remove Old MagicMirror Versions
###############################################################################
# Remove versioned MagicMirror directories, excluding the currently set
# MagicMirror version.
#
# Args:
#   _mirror_target: str full version (vx.x.x) to install.

- name: 'clean | find existing installations'
  ansible.builtin.find:
    paths:     '{{ mirror_default_install_dir }}'
    file_type: 'directory'
    use_regex: true
    patterns:
      - '.*mirror-.*'
    recurse:   false
  register: _mirror_existing_installs

- name: 'clean | remove old versions'
  ansible.builtin.file:
    path:  '{{ item.path }}'
    state: 'absent'
  loop: '{{ _mirror_existing_installs.files }}'
  when: |
    _mirror_target != item.path.split("-", 1)[-1] and
    mirror_delete_old_versions
