---
###############################################################################
# MagicMirror Configuration
###############################################################################
# Configure MagicMirror via config and custom css.
#
# Args:
#   _mirror_install_dir: str versioned install location.
#
# Referece:
# * https://docs.magicmirror.builders/getting-started/installation.html

- name: 'config | set mirror config'
  ansible.builtin.template:
    src:   'config.js.j2'
    dest:  '{{ _mirror_install_dir }}/config.js'
    owner: '{{ mirror_user }}'
    group: '{{ mirror_group }}'
    mode:  0640
  notify:  'reboot mirror'

- name: 'config | set custom.css'
  ansible.builtin.copy:
    src:   '{{ mirror_custom_css }}'
    dest:  '{{ _mirror_install_dir }}/css/custom.css'
    owner: '{{ mirror_user }}'
    group: '{{ mirror_group }}'
    mode:  0440
  when: mirror_custom_css|length > 0
  notify:  'reboot mirror'

- name: 'config | remove custom.css'
  ansible.builtin.file:
    path:  '{{ _mirror_install_dir }}/css/custom.css'
    state: 'absent'
  when: mirror_custom_css|length == 0
  notify:  'reboot mirror'
