---
###############################################################################
# MagicMirror Github Download
###############################################################################
# Download and validate the mirror package from github, using the specified
# version.
#
# Args:
#   _mirror_install_dir: str versioned install location.
#   _mirror_target: str full version (vx.x.x) to install.
#   _mirror_url: str download url for current release.
#   _mirror_archive: str local versioned archive location.
#
# Generates:
#   _mirror_install_stat: stat object for the versioned install location.

- name: 'download | check local versioned install directory'
  ansible.builtin.stat:
    path: '{{ _mirror_install_dir }}'
  register: _mirror_install_stat

- name: 'download | download mirror {{ _mirror_target }}'
  ansible.builtin.get_url:
    url:    '{{ _mirror_url }}'
    dest:   '{{ _mirror_archive }}'
    mode:   0644
    owner:  '{{ mirror_user }}'
    group:  '{{ mirror_group }}'
  register: _mirror_download
  until: _mirror_download is succeeded
  retries: 5
  delay: 2
  when: not _mirror_install_stat.stat.exists
