---
###############################################################################
# MagicMirror Custom Module Configuration
###############################################################################
# Download and install custom modules for MagicMirror.
#
# Args:
#   _mirror_install_dir: str versioned install location.
#   _mirror_modules: list of dicts containing modules requiring installation.
#
# Reference:
# * https://docs.magicmirror.builders/modules/configuration.html

- name: 'modules | add custom modules (may take a while)'
  ansible.builtin.debug:
    msg: |
      Custom modules are being installed. This will take a few minutes.

- name: 'modules | cloning custom modules' # noqa git-latest always checkout latest mirror modules.
  ansible.builtin.git:
    repo: '{{ item.source }}'
    dest: '{{ _mirror_install_dir }}/modules/{{ item.setting.module }}'
    clone: true
    depth: 1
    recursive: true
    update: true
  loop: '{{ _mirror_modules }}'

# Set specific permissions (missed if git sets permissions).
# Reference: https://github.com/ansible/ansible/issues/51601
- name: 'modules | setting custom module permissions'
  ansible.builtin.file:
    path:    '{{ _mirror_install_dir }}/modules/{{ item.setting.module }}'
    owner:   '{{ mirror_user }}'
    group:   '{{ mirror_group }}'
    mode:    'a-st,o-rwx'
    recurse: true
    state:   'directory'
  loop: '{{ _mirror_modules }}'

- name: 'modules | install custom modules'
  ansible.builtin.shell: '{{ item.install }} 2>/dev/null'
  args:
    chdir: '{{ _mirror_install_dir }}/modules/{{ item.setting.module }}'
  become: true
  become_user: '{{ mirror_user }}'
  # Reference: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true
  when: item.install|default('')|length > 0
  loop: '{{ _mirror_modules }}'
