---
###############################################################################
# MagicMirror NPM Configuration
###############################################################################
# Configure and update NPM dependencies for MagicMirror.
#
# Args:
#   _mirror_install_dir: str versioned install location.
#
# Referece:
# * https://docs.magicmirror.builders/getting-started/installation.html
# * https://docs.magicmirror.builders/configuration/autostart.html#using-systemd-systemctl

- name: 'npm | add packages (may take a while)'
  ansible.builtin.debug:
    msg: |
      NPM packages are being installed. This will take a few minutes.

- name: 'npm | install core' # noqa no-changed-when always execute
  ansible.builtin.shell: '/usr/bin/npm install 2>/dev/null'
  args:
    chdir: '{{ _mirror_install_dir }}'
  become: true
  become_user: '{{ mirror_user }}'
  # Reference: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true

- name: 'npm | install dependencies'
  community.general.npm:
    path:  '{{ _mirror_install_dir }}'
    state: 'latest'
  become: true
  become_user: '{{ mirror_user }}'
  # Reference: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true

- name: 'npm | update' # noqa no-changed-when always execute
  ansible.builtin.command: '/usr/bin/npm update'
  args:
    chdir: '{{ _mirror_install_dir }}'
  become: true
  become_user: '{{ mirror_user }}'
  # Reference: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true

- name: 'npm | apply latest security patches' # noqa no-changed-when always execute
  ansible.builtin.command: '/usr/bin/npm audit fix'
  args:
    chdir: '{{ _mirror_install_dir }}'
  become: true
  become_user: '{{ mirror_user }}'
  # Reference: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true
